### ISSUE TITLE
When deploying to a Pantheon multidev from a local env, post:install tries to migrate to the local env

### ISSUE THREAD

**Issue by bdimaggio** [thinkshout/robo-drupal#11]
`robo post_install` has some logic that only tries to run a migration when it's taking place on Circle. If `getenv('CIRCLECI')` doesn't return true, this command assumes you want to migrate to your local. 

In order to address this, I'd like to have local environments avoid checking or messing with .env's `TERMINUS_ENV` file at all, instead looking for an option called "multidev" in `postInstall` to figure where to migrate content to. I'd also like to add a Boolean "full_migration" option to the command so that it's possible to pull in all the content (useful when deploying to a dev environment). Finally, I want to add multiple `drush cr` calls when deploying to a multidev, as I have pretty consistently found that that's the only way to make drush believe that the `migrate_tools` module is installed, and that therefore the mim command is available.

I have ugly code doing this in LVHN's RoboFile.php, and I'd like to pretty it up and add it here.

**Comment by mariacha** [comment]
We're not really deploying from our local machines much. I'm closing this one.
