### ISSUE TITLE
New installs with stable databases require you to manually make the database

### ISSUE THREAD

**Issue by mariacha** [thinkshout/robo-drupal#16]
If you run `robo install` on a project with a stable database, but have never installed previously, the database configured in `robo configure` doesn't exist, so your install fails.

**Comment by rjacobsen0** [comment]
To recreate:
Pick a project that has gone live.
Delete that project's whole database on local.
Try to run robo import:Local
You should see an error. We want it to tell you your database is missing or, better yet, it creates the database for you.
