### ISSUE TITLE
Needed: Better robo install database pull

### ISSUE THREAD

**Issue by mariacha** [thinkshout/robo-drupal#17]
Doing a `robo install` and pulling a database from pantheon succeeds about a half to a quarter of the time, likely because Pantheon isn't great at supporting it.

- [ ] See if we can get more stability from using a terminus command instead.

**Comment by tauno** [comment]
Lando might provide some ideas as well - or maybe we just borrow their script: https://github.com/lando/lando/blob/master/plugins/lando-recipes/recipes/pantheon/pull.sh

It looks to use drush as well.

**Comment by mariacha** [comment]
Interesting -- they use sql-dump instead of sql-sync. I wonder if that's better? If I'm reading this right, they basically do this:

```
drush @pantheon.$SITE.$DATABASE sql-dump | mysql --user=root --password=root --database=[whatever] --host=database --port=3306"
``` 

Yeah -- that does seem to work! At least for my initial tests. And it's pretty freaking fast too. It doesn't use terminus, but I bet that's not unavoidable...

**Comment by mariacha** [comment]
Update: We can try for this command instead:

```
terminus remote:drush lvhn.live -- sql-dump | drush sqlc
``

**Comment by mariacha** [comment]
This was also done and will be part of the 2.0 release
