### ISSUE TITLE
Config_installer incompatibility with 8.6 and robo install

### ISSUE THREAD

**Issue by mariacha** [thinkshout/robo-drupal#18]
Drupal 8.6 adds the ability to install from a directory instead of a specific profile, which means we don't really need config_installer anymore.

See this issue:
https://www.drupal.org/project/config_installer/issues/2910643

and its related issue:
https://www.drupal.org/project/drupal/issues/2788777

Using config installer is, in fact, breaking if you are installing from a fresh database (you have to remove the profile from the list of modules in your core.extension.yml file, see: 
https://github.com/thinkshout/drupal-project/commit/e49c76585fa27236649e9893d73f15be8b501309

BUT if you remove that line from a robo install for a NOT fresh database, it also breaks. 

We need to be able to run both, as circle uses a fresh db every time, and local development uses an existing DB.

Possible solutions:
- Install the minimal profile and just immediately drush cim -- I'm doing this on Humane society for now: https://github.com/thinkshout/hsus/pull/706/files -- this isn't an ideal solution, but works for HSUS, were the db is stable.
- Use the `config-dir` option available in the `drush si` command. This should work, and is probably better, but I got a warning from drush about "each" being depricated, which failed my tests:
https://circleci.com/gh/thinkshout/hsus/1843?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by mariacha** [comment]
Here's a very discrete set of changes that goes with the first option and upgrades from D8.5 -> D8.6:

https://github.com/thinkshout/wfw/pull/393/files

**Comment by wxactly** [comment]
@mariacha - you could try this new option, see if it works better for drupal 8.6: `--existing-config`

https://github.com/drush-ops/drush/pull/3625

It's a little confusing to me which option does what, but seems like it's worth a try!

**Comment by mariacha** [comment]
Ahh, and it looks like the `--existing config` option was only added on drush 9.x anyway. So drush 9.4.0 will have the sweet spot of that command AND not require "consolidation/annotated-command": "^2.9.1" (which was added with drush 9.5.0)

**Comment by unclegcb** [comment]
I ran into this on LATW and ended up making direct pushes to Pantheon to override the core.extensions.yml just to get things done. Interested in working out a solution but don't have my head entirely wrapped around it yet!

**Comment by unclegcb** [comment]
Alright, I tried the suggested fix on LATW, and it ran well on Circle:

**Comment by mariacha** [comment]
Change is merged into master and will be available in the 2.0 release
