### ISSUE TITLE
Project names with punctuation end up with mismatched db names

### ISSUE THREAD

**Issue by tauno** [thinkshout/robo-drupal#2]
A project name of `bene-dev` on the `master` branch results in a db name like `benedev_master` while the environment configuration uses `bene-dev_master`

**Comment by mariacha** [comment]
How to replicate:

On any project, create a new branch with a dash in it. For example, if you were to test this on teaching-tolerance:

```
git checkout -b my-test-branch
```

Run `robo configure`

Open your .env file and see that the database is now trying to connect to `teaching-tolerance_my-test-branch` (or something like that) but it's not possible to name databases with dashes like that.

The task here is to remove dashes from the name of the database, so it's something like:

```
teaching_tolerance_my_test_branch
```

when you run `robo configure`
