### ISSUE TITLE
Document the methods in Robo Drupal

### ISSUE THREAD

**Issue by mariacha** [thinkshout/robo-drupal#43]
- [x] Go through the methods on https://github.com/thinkshout/robo-drupal/blob/master/src/Tasks.php and create documentation in the wiki of this project that lists out the following:
- [x] The user-friendly docblock comments
- [x] List any `public` functions as being available from the command line.
- [x] Add "public" to any public functions (in code).
- [x] Note that the command you run when you run these via command line, follows the syntax of `robo pull:config`(colon:middle)  which runs the method `pullConfig` (lowerCamelCase)

- [x] See if the documentation below could be autogenerated somehow. (Research task.)

- [ ] Find out if we can do doxygen on circle on commit and auto-commit the output here.

**Comment by rjacobsen0** [comment]
Here's how to run Doxygen.
1. Download an executable here: http://www.doxygen.nl/download.html
2. Move the executable into your Applications folder
3. Run it (may need to hold control while starting it to give permission for it to run).
4. Run through the wizard to get set up.
5. On the Expert tab (Project topic) check JAVADOC_AUTOBRIEF checkbox
6. Run Doxygen
7. Look at output in the location you specified. Mine is here: file:///Users/rjacobsen0/Projects/robo-drupal-docs/html/index.html

**Comment by rjacobsen0** [comment]
There's another way to get Doxygen: brew install doxygen
After you do that you can run doxygen from the command line.
I created a config file called robo-drupalDoxygenConfig and you can then call it like this
doxygen robo-drupalDoxygenConfig
The config file specifies the output will be put in OUTPUT_DIRECTORY       = docs
and it always goes in a subdirectory called html. And it says the input comes from 
INPUT                  = src
which will pick up Tasks.php.

**Comment by rjacobsen0** [comment]
The next task is to output the documentation to https://thinkshout.github.io/robo-drupal-docs/index.html or https://thinkshout.github.io/robo-drupal/index.html.

To put it in https://thinkshout.github.io/robo-drupal-docs/index.html I created a new github repo called robo-drupal-docs and turned on github pages (https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages).

To put them in https://thinkshout.github.io/robo-drupal the docs need to go in robo-drupal repo in a subdirectory called /docs and we need to visit https://github.com/thinkshout/robo-drupal/settings to set this up as an admin.

Then either way, we need to edit the file .circleci/config.yml and make the commands to generate documentation with doxygen and then put the files in the correct location and commit them to the repo.

**Comment by mariacha** [comment]
This is so awesome. I'm calling it closed.
