### ISSUE TITLE
chmod of default file not working.

### ISSUE THREAD

**Issue by mariacha** [thinkshout/robo-drupal#6]
This line:
https://github.com/thinkshout/robo-drupal/blob/master/src/Tasks.php#L397

assumes we'll be getting the sftp command line string from Pantheon but we aren't getting it anymore. I have to assume it's an upstream Robo change.

This issue:
https://github.com/consolidation/Robo/issues/382

says we should be using a different method to get stuff from the system.

The chmod of settings files just isn't happening anymore.

Perhaps there's a way to do this without reading the SFTP command? Drush exec?

**Comment by unclegcb** [comment]
Well, I got us this far:

```
Running sftp -b - -o Port=2222 develop.a9177577-e604-4592-8708-802a0a852307@appserver.develop.a9177577-e604-4592-8708-802a0a852307.drush.in << EOF
chmod 644 code/web/sites/default
chmod 644 code/web/sites/default/settings.php
EOF
Warning: Permanently added '[appserver.develop.a9177577-e604-4592-8708-802a0a852307.drush.in]:2222,[130.211.202.80]:2222' (RSA) to the list of known hosts.

sftp> chmod 644 code/web/sites/default
sftp> chmod 644 code/web/sites/default/settings.php
Couldn't setstat on "/srv/bindings/1c30651192e04aa6b498676a6b27105e/code/web/sites/default/settings.php": Permission denied
```
