### ISSUE TITLE
Any changes to blacklist nonetheless appear in main config directory

### ISSUE THREAD

**Issue by bdimaggio** [thinkshout/robo-drupal#60]
When you either add a module to the blacklist, or change the configuration of one that's already on it, the resulting config file changes always (or at least often) wind up in /config rather than /config-local. I think that's because of a poorly-documented part of the module that only seems to be mentioned [here](https://www.drupal.org/docs/8/modules/configuration-split/creating-a-simple-split-configuration-dev-modules-only-in-dev#s-create-a-configuration-split):
> Keep the _Machine name_ the same as the _Folder_.

This change assumes that you've changed both the machine name and the destination folder of your split to `config_local`. If this works well for FRHO, we can apply that change to thinkshout/drupal-project.

**Comment by mariacha** [comment]
I actually think this would be solved by https://github.com/thinkshout/drupal-integrations/issues/14 and https://github.com/thinkshout/robo-drupal/issues/73, so I'm going to close this one.
