### ISSUE TITLE
Add progress bar for local import

### ISSUE THREAD

**Issue by mariacha** [thinkshout/robo-drupal#68]
SEe this example:
https://github.com/thinkshout/lvhn/pull/4804/files

Add a "pv" check to the `importLocal` command that sees if you've got it installed. If you do, alter the `drush_import_database` line to: `'drush_import_database' => 'pv ../vendor/database.sql.gz | zcat | drush @self sqlc`. If you don't let people know we suggest adding the `pv` library with `brew install pv`, but don't fail the import.

**Comment by bdimaggio** [comment]
At the risk of being hasty, I also proposed this over in https://github.com/thinkshout/ts_environment/pull/49. Wouldn't require a change here per se, but would just take the burden of installing `pv` off future devs.
